### ISSUE TITLE
ValueError uncaught webrtc bug

### ISSUE THREAD

**Issue by adminy** [balenalabs/balena-cam#104]
Logs
```log
 balena-cam  ======== Running on http://0.0.0.0:80 ========
 balena-cam  (Press CTRL+C to quit)
 balena-cam  /usr/local/lib/python3.5/dist-packages/pyee/_base.py:83: RuntimeWarning: coroutine 'on_iceconnectionstatechange' was never awaited
 balena-cam    f(*args, **kwargs)
 balena-cam  Task exception was never retrieved
 balena-cam  future: <Task finished coro=<RTCPeerConnection.__connect() done, defined at /usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py:554> exception=ValueError("'e855c082-1def-43a6-8696-b6c45879f59a.local' does not appear to be an IPv4 or IPv6 address",)>
 balena-cam  Traceback (most recent call last):
 balena-cam    File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
 balena-cam      result = coro.send(None)
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcpeerconnection.py", line 559, in __connect
 balena-cam      await iceTransport.start(self.__remoteIce[transceiver])
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/aiortc/rtcicetransport.py", line 284, in start
 balena-cam      await self._connection.connect()
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/aioice/ice.py", line 356, in connect
 balena-cam      if (protocol.local_candidate.can_pair_with(remote_candidate) and
 balena-cam    File "/usr/local/lib/python3.5/dist-packages/aioice/candidate.py", line 114, in can_pair_with
 balena-cam      b = ipaddress.ip_address(other.host)
 balena-cam    File "/usr/lib/python3.5/ipaddress.py", line 54, in ip_address
 balena-cam      address)
 balena-cam  ValueError: 'e855c082-1def-43a6-8696-b6c45879f59a.local' does not appear to be an IPv4 or IPv6 address
```

**Comment by Sheng-IoT** [comment]
I am having the exact same issue on my Raspberry Pi 4b, same error message in the log.
I checked the local address of the webcam. Although it won't return 404 or an error message, it doesn't show anything:
![image](https://user-images.githubusercontent.com/87348555/179874777-cf19bc94-4583-49e5-ae8d-c40d2c9dc475.png)

then I checked the public URL, this time I got an error message about port 80

![image](https://user-images.githubusercontent.com/87348555/179874747-2f661b85-ddac-4851-8488-66f2cc91f888.png)

another weird thing is that the device is online apparently, but on the dashboard, it tells me that it's offline:

![image](https://user-images.githubusercontent.com/87348555/179875122-21530121-35cc-4dcd-8764-bb6dacf5310b.png)

Can someone please offer me some assistances or suggestions?
